import type { CityImage } from "@/lib/city-image"

export const SAN_DIEGO_CITY_IMAGES: Record<string, CityImage> = {
  "carlsbad-ca": {
    city: "Carlsbad",
    src: "/city/san-diego-county/carlsbad-ca.webp",
    alt: "Leo Carrillo Ranch in Carlsbad, California",
    attractionLabel: "Leo Carrillo Ranch & Carlsbad",
    creator: "Ken Lund",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Leo_Carrillo_Ranch,_Carlsbad,_California_(15473262218).jpg",
  },
  "chula-vista-ca": {
    city: "Chula Vista",
    src: "/city/san-diego-county/chula-vista-ca.webp",
    alt: "Chula Vista Bayfront and marina in San Diego County",
    attractionLabel: "Chula Vista Bayfront",
    creator: "Port of San Diego",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ChulaVista_Bayfront.jpg",
  },
  "coronado-ca": {
    city: "Coronado",
    src: "/city/san-diego-county/coronado-ca.webp",
    alt: "Hotel del Coronado on Coronado Island, California",
    attractionLabel: "Hotel del Coronado",
    creator: "Djh57",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hotel_del_Coronado.JPG",
  },
  "del-mar-ca": {
    city: "Del Mar",
    src: "/city/san-diego-county/del-mar-ca.webp",
    alt: "Del Mar coastline and racetrack in San Diego County",
    attractionLabel: "Del Mar Coast & Racetrack",
    creator: "Intersofia",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Del-Mar-Race-Track.jpg",
  },
  "el-cajon-ca": {
    city: "El Cajon",
    src: "/city/san-diego-county/el-cajon-ca.webp",
    alt: "Downtown gateway sign in El Cajon, California",
    attractionLabel: "Downtown El Cajon",
    creator: "Namiwoo",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:El_Cajon.jpg",
  },
  "encinitas-ca": {
    city: "Encinitas",
    src: "/city/san-diego-county/encinitas-ca.webp",
    alt: "Moonlight Beach and coastline in Encinitas, California",
    attractionLabel: "Moonlight Beach",
    creator: "Ohnoitsjamie",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:MoonlightBeach_EncinitasCA.jpg",
  },
  "escondido-ca": {
    city: "Escondido",
    src: "/city/san-diego-county/escondido-ca.webp",
    alt: "Aerial view of downtown Escondido, California",
    attractionLabel: "Downtown Escondido",
    creator: "Mark Skovorodko",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Mark_Skovorodko_Photography_-_Downtown_Escondido_Aerial.jpg",
  },
  "imperial-beach-ca": {
    city: "Imperial Beach",
    src: "/city/san-diego-county/imperial-beach-ca.webp",
    alt: "Imperial Beach public art and pier in California",
    attractionLabel: "Imperial Beach Pier",
    creator: "Henryk Kotowski",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Imperial_beach_ca_1.jpg",
  },
  "la-jolla-ca": {
    city: "La Jolla",
    src: "/city/san-diego-county/la-jolla-ca.webp",
    alt: "La Jolla Shores and coastal cliffs in San Diego, California",
    attractionLabel: "La Jolla Shores",
    creator: "Dirk Hansen",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:La_Jolla_Shores_view.jpg",
  },
  "la-mesa-ca": {
    city: "La Mesa",
    src: "/city/san-diego-county/la-mesa-ca.webp",
    alt: "Amaya Drive trolley station in La Mesa, California",
    attractionLabel: "La Mesa & Amaya Drive",
    creator: "Stickpen",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Amayatrolley.jpg",
  },
  "lemon-grove-ca": {
    city: "Lemon Grove",
    src: "/city/san-diego-county/lemon-grove-ca.webp",
    alt: "Lemon Grove Library in Lemon Grove, California",
    attractionLabel: "Lemon Grove Civic Center",
    creator: "Bookbabe",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lemon_Grove,_CA_Library_(cropped).jpg",
  },
  "national-city-ca": {
    city: "National City",
    src: "/city/san-diego-county/national-city-ca.webp",
    alt: "Mile of Cars landmark in National City, California",
    attractionLabel: "National City Mile of Cars",
    creator: "Der-wuppertaler",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:USA_CA_NationalCity_Center_002_2013_-_Mile_of_Cars.jpg",
  },
  "oceanside-ca": {
    city: "Oceanside",
    src: "/city/san-diego-county/oceanside-ca.webp",
    alt: "Oceanside beachfront homes and coastline in California",
    attractionLabel: "Oceanside Beachfront",
    creator: "Scotwriter21",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Oceanside_SW01_(cropped).jpg",
  },
  "poway-ca": {
    city: "Poway",
    src: "/city/san-diego-county/poway-ca.webp",
    alt: "Twin Peaks and neighborhoods in Poway, California",
    attractionLabel: "Twin Peaks & Poway",
    creator: "Perdelsky",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:TwinPeaksPoway1.jpg",
  },
  "san-diego-ca": {
    city: "San Diego",
    src: "/city/san-diego-county/san-diego-ca.webp",
    alt: "Sunny downtown San Diego skyline viewed across the bay",
    attractionLabel: "Downtown San Diego & Bay",
    creator: "Amantonacci",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sunny_San_Diego_Shoreline.jpg",
  },
  "san-marcos-ca": {
    city: "San Marcos",
    src: "/city/san-diego-county/san-marcos-ca.webp",
    alt: "San Marcos neighborhoods and Discovery Lake in California",
    attractionLabel: "San Marcos & Discovery Lake",
    creator: "Taylorj661",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:SanMarcos.jpg",
  },
  "santee-ca": {
    city: "Santee",
    src: "/city/san-diego-county/santee-ca.webp",
    alt: "Mission Trails landscape beside Santee, California",
    attractionLabel: "Santee & Mission Trails",
    creator: "Dmadeo",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mission-trails-regional-park.JPG",
  },
  "solana-beach-ca": {
    city: "Solana Beach",
    src: "/city/san-diego-county/solana-beach-ca.webp",
    alt: "Fletcher Cove and coastline in Solana Beach, California",
    attractionLabel: "Fletcher Cove",
    creator: "Rosalynn Carmen",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Fletcher_Cover,_Solana_Beach_California_-_panoramio.jpg",
  },
  "vista-ca": {
    city: "Vista",
    src: "/city/san-diego-county/vista-ca.webp",
    alt: "Vista Village gateway in Vista, California",
    attractionLabel: "Vista Village",
    creator: "City of Vista",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vista_Gateway.jpg",
  },
}

export const SAN_DIEGO_CITY_IMAGE_MAP = Object.fromEntries(
  Object.entries(SAN_DIEGO_CITY_IMAGES).map(([slug, image]) => [slug, image.src]),
)

export function getSanDiegoCityImage(citySlug: string): CityImage | null {
  return SAN_DIEGO_CITY_IMAGES[citySlug] ?? null
}
