import assert from "node:assert/strict"
import { buildPropertyContactHref, isInternationalPhone, isValidTimeZone, isValidTourDate, todayInTimeZone, readContactContext, safePropertyPageUrl } from "../contact-context"

const legacy = readContactContext(new URLSearchParams("property=1176571070"))
assert.equal(legacy.listingKey, "1176571070")
assert.match(legacy.message, /1176571070/)

const href = buildPropertyContactHref({ listingKey: "1176571070", propertyAddress: "1658 N Hunters, Orange, CA", propertyPageUrl: "/properties/1658-n-hunters/1176571070" })
const context = readContactContext(new URL(href, "https://crowncoastalhomes.com").searchParams)
assert.equal(context.propertyAddress, "1658 N Hunters, Orange, CA")
assert.equal(context.propertyPageUrl, "https://crowncoastalhomes.com/properties/1658-n-hunters/1176571070")
assert.match(context.message, /virtual tour/)
assert.equal(new URL(href, "https://crowncoastalhomes.com").hash, "#contact-form")

assert.equal(safePropertyPageUrl("javascript:alert(1)"), "")
assert.equal(safePropertyPageUrl("https://other.example/properties/fake"), "")
assert.equal(safePropertyPageUrl("//other.example/properties/fake"), "")
assert.equal(safePropertyPageUrl("/admin"), "")
assert.equal(readContactContext(new URLSearchParams("property=12&message=My+own+question")).message, "My own question")
assert.equal(readContactContext(new URLSearchParams("listingKey=34&property=12")).listingKey, "34")
assert.match(readContactContext(new URLSearchParams("inquiry=valuation&address=1+Main+St")).message, /home valuation for: 1 Main St/)
assert.match(readContactContext(new URLSearchParams("inquiry=financing&propertyAddress=1+Main+St")).message, /financing options for 1 Main St/)
assert.equal(isInternationalPhone("+44 20 7946 0958"), true)
assert.equal(isInternationalPhone("+1 (858) 305-4362"), true)
assert.equal(isInternationalPhone(""), true)
assert.equal(isInternationalPhone("abcdefghij"), false)
assert.equal(isInternationalPhone("123"), false)
assert.equal(isValidTimeZone("Europe/London"), true)
assert.equal(isValidTimeZone("America/Los_Angeles"), true)
assert.equal(isValidTimeZone("invented/zone"), false)
const midnight = new Date("2026-09-06T02:00:00Z")
assert.equal(todayInTimeZone("Europe/London", midnight), "2026-09-06")
assert.equal(todayInTimeZone("America/Los_Angeles", midnight), "2026-09-05")
assert.equal(isValidTourDate("2026-09-05", "America/Los_Angeles", midnight), true)
assert.equal(isValidTourDate("2026-09-05", "Europe/London", midnight), false)
assert.equal(isValidTourDate("2026-09-06", "Europe/London", midnight), true)
assert.equal(isValidTourDate("2026-02-30", "Europe/London", midnight), false)
assert.equal(isValidTourDate("tomorrow", "Europe/London", midnight), false)
assert.equal(isValidTourDate("2026-09-06", "", midnight), false)
console.log("contactContext: all assertions passed")
